[lapce-emmet.languageFeatures]
references = true
definition = true
typeDefinition = true
callHierarchy = true
hover = true
rename = true
renameFileRefactoring = true
signatureHelp = true
codeAction = true
workspaceSymbol = true
diagnostics = true
documentHighlight = true
documentLink = true
semanticTokens = false
[lapce-emmet.languageFeatures.schemaRequestService]
getDocumentContentRequest = true
[lapce-emmet.languageFeatures.codeLens]
showReferencesNotification = true
[lapce-emmet.languageFeatures.completion]
defaultTagNameCase = 'both'
defaultAttrNameCase = 'kebabCase'
getDocumentNameCasesRequest = false
getDocumentSelectionRequest = false
[lapce-emmet.documentFeatures]
selectionRange = true
foldingRange = true
linkedEditingRange = true
documentSymbol = true
documentColor = true