name = "lapce-html"
version = "0.0.1"
author = "CroxxN"
display-name = "HTML"
description = "HTML lsp for Lapce"
wasm = "bin/lapce-html.wasm"

[activation]
language = ["html","html"]
workspace-contains = [ "*/*.html", "*/*.htm"]

[config."volt.serverPath"]
default = ""
description = "Path to html-language-server"

[config."volt.serverArgs"]
default = ["--stdio"]
description = "LSP server arguments to pass when launching"
